package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.ToString;

@DynamoDBTable(tableName = "DaysSubscription")
@ToString
@Data
public class DaysSubscription {
    private String startDate;
    private String endDate;
    private String daysSubscriptionId;

    @DynamoDBAttribute(attributeName = "startDate")
   public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @DynamoDBAttribute(attributeName = "endDate")
    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    @DynamoDBHashKey(attributeName="daysSubscriptionId")
    @DynamoDBAutoGeneratedKey
    public String getDaysSubscriptionId() {
        return daysSubscriptionId;
    }

    public void setDaysSubscriptionId(String daysSubscriptionId) {
        daysSubscriptionId = daysSubscriptionId;
    }
}
