package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@DynamoDBTable(tableName = "DaysSubscription")
@ToString
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class DaysSubscription {
    private String startDate;
    private String endDate;
    private String daysSubscriptionId;

}
