package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;

import java.time.LocalDate;

public class GamesSubscription {
    private Integer gamesLeft;
    private String gamesSubscriptionId;
    private LocalDate endDate;

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    @DynamoDBAttribute(attributeName="gamesLeft")
    public Integer getGamesLeft() {
        return gamesLeft;
    }

    public void setGamesLeft(Integer gamesLeft) {
        this.gamesLeft = gamesLeft;
    }

    @DynamoDBAttribute(attributeName="gamesSubscriptionId")
    @DynamoDBAutoGeneratedKey
    public String getGamesSubscriptionId() {
        return gamesSubscriptionId;
    }

    public void setGamesSubscriptionId(String gamesSubscriptionId) {
        this.gamesSubscriptionId = gamesSubscriptionId;
    }
}
