package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;

public class GamesSubscription {
    private Integer gamesLeft;
    private String gamesSubscriptionId;

    @DynamoDBAttribute(attributeName="gamesLeft")
    public Integer getGamesLeft() {
        return gamesLeft;
    }

    public void setGamesLeft(Integer gamesLeft) {
        this.gamesLeft = gamesLeft;
    }

    @DynamoDBAttribute(attributeName="gamesSubscriptionId")
    @DynamoDBAutoGeneratedKey
    public String getGamesSubscriptionId() {
        return gamesSubscriptionId;
    }

    public void setGamesSubscriptionId(String gamesSubscriptionId) {
        this.gamesSubscriptionId = gamesSubscriptionId;
    }
}
