package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "GamesSubscription")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class GamesSubscription {
    private Integer gamesLeft;
    private String gamesSubscriptionId;
    private String endDate;

}
