package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.time.LocalDate;

@DynamoDBTable(tableName = "LoyaltyPass")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LoyaltyPass {
    private String passId;
    private Integer price;
    private String location;

    public static enum PassType {
        DAY_PASS,
        GAME_PASS;
    }

    private PassType passType;
    private Integer numberOfGames;
    private Integer validityPeriodInDays;
    private LocalDate createdDate;
    private LocalDate lastUpdatedDate;

    @DynamoDBAttribute(attributeName = "validityPeriodInDays")
    public Integer getValidityPeriodInDays() {
        return validityPeriodInDays;
    }

    public void setValidityPeriodInDays(Integer validityPeriodInDays) {
        this.validityPeriodInDays = validityPeriodInDays;
    }

    @DynamoDBAttribute(attributeName = "createdDate")
    public LocalDate getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(LocalDate createdDate) {
        this.createdDate = createdDate;
    }

    @DynamoDBAttribute(attributeName = "lastUpdatedDate")
    public LocalDate getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(LocalDate lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }


    @DynamoDBHashKey(attributeName = "passId")
    @DynamoDBAutoGeneratedKey()
    public String getPassId() {
        return passId;
    }

    public void setPassId(String passId) {
        this.passId = passId;
    }

    @DynamoDBAttribute(attributeName = "price")
    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    @DynamoDBAttribute(attributeName = "location")
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @DynamoDBAttribute(attributeName = "passType")
    @DynamoDBTypeConvertedEnum
    public PassType getPassType() {
        return passType;
    }

    public void setPassType(PassType passType) {
        this.passType = passType;
    }


    @DynamoDBAttribute(attributeName = "numberOfGames")
    public Integer getNumberOfGames() {
        return numberOfGames;
    }

    public void setNumberOfGames(Integer numberOfGames) {
        this.numberOfGames = numberOfGames;
    }
}

