package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.ToString;

@DynamoDBTable(tableName = "MonthlyPass")
@ToString
public class MonthlyPass {
    private String passId;
    private Integer price;
    private String location;
    private PassType passType;
    private Integer durationInDays;
    private Integer numberOfGames;
    private String validityPeriod;

    public enum PassType {
        DAY_PASS,
        GAME_PASS;
    }

    @DynamoDBHashKey(attributeName="passId")
    @DynamoDBAutoGeneratedKey()
    public String getPassId() {
        return passId;
    }

    public void setPassId(String passId) {
        this.passId = passId;
    }

    @DynamoDBHashKey(attributeName="price")
    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    @DynamoDBHashKey(attributeName="location")
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @DynamoDBHashKey(attributeName="passType")
    public PassType getPassType() {
        return passType;
    }

    public void setPassType(PassType passType) {
        this.passType = passType;
    }

    @DynamoDBHashKey(attributeName="durationInDays")
    public Integer getDurationInDays() {
        return durationInDays;
    }

    public void setDurationInDays(Integer durationInDays) {
        this.durationInDays = durationInDays;
    }

    @DynamoDBHashKey(attributeName="numberOfGames")
    public Integer getNumberOfGames() {
        return numberOfGames;
    }

    public void setNumberOfGames(Integer numberOfGames) {
        this.numberOfGames = numberOfGames;
    }

    @DynamoDBHashKey(attributeName="validityPeriod")
    public String getValidityPeriod() {
        return validityPeriod;
    }

    public void setValidityPeriod(String validityPeriod) {
        this.validityPeriod = validityPeriod;
    }


}
