package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.data.annotation.Id;


@DynamoDBTable(tableName = "Pass")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Pass {

    public static enum PassType {
        LimitedGames,
        LimitedDays
    }
    public static enum Status {
        Active,
        Expired
    }

    @DynamoDBRangeKey(attributeName = "passId")
    @DynamoDBAutoGeneratedKey
    private String passId;

    @DynamoDBHashKey(attributeName = "cityId")
    private String cityId;

    @DynamoDBTypeConvertedEnum
    private PassType passType;

    private Integer totalGames;

    private Integer totalDays;

    private String title;

    private Double price;

    @DynamoDBTypeConvertedEnum
    private Status status;

    @Id
    @DynamoDBIgnore
    private PassKey passKey;
}

