package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;


@DynamoDBTable(tableName = "Pass")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Pass {

    public static enum PassType {
        LimitedGames,
        LimitedDays
    }
    public static enum Status {
        Active,
        Expired
    }

    @DynamoDBRangeKey(attributeName = "passId")
    @DynamoDBAutoGeneratedKey
    private String passId;

    @DynamoDBHashKey(attributeName = "cityId")
    private String cityId;

    @DynamoDBAttribute(attributeName = "passType")
    @DynamoDBTypeConvertedEnum
    private PassType passType;

    @DynamoDBAttribute(attributeName = "totalGames")
    private Integer totalGames;

    @DynamoDBAttribute(attributeName = "totalDays")
    private Integer totalDays;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "price")
    private Double price;

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedEnum
    private Status status;
}

