package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.flickmatch.platform.dynamodb.model.Event.EventId;

import lombok.*;
import org.springframework.data.annotation.Id;


@DynamoDBTable(tableName = "Pass")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Pass {
    
    @DynamoDBHashKey(attributeName="cityId")
    public String getCityId() {
        return this.passKey != null ? this.passKey.getCityId() : null;
    }

    public void setCityId(String cityId) {
        if (this.passKey == null) {
            this.passKey = new PassKey();
        }
        this.passKey.setCityId(cityId);
    }

    @DynamoDBRangeKey(attributeName = "passId")
    @DynamoDBAutoGeneratedKey
    public String getPassId() {
        return this.passKey != null ? this.passKey.getPassId() : null;
    }

    public void setPassId(String passId) {
        if (this.passKey == null) {
            this.passKey = new PassKey();
        }
        this.passKey.setPassId(passId);
    }

    private String passType;

    private Integer totalGames;

    private Integer totalDays;

    private String title;

    private Double price;

    private String status;

    // This is a composite key made up of cityId and passId
    @Id
    private PassKey passKey;

    @Builder
    @Getter
    @Setter
    public static class PassKey {
    
        @DynamoDBHashKey(attributeName="cityId")
        private String cityId;

        @DynamoDBRangeKey(attributeName = "passId")
        @DynamoDBAutoGeneratedKey
        private String passId;

        PassKey() {
        }

        PassKey(String passId, String cityId) {
            this.passId = passId;
            this.cityId = cityId;
        }
    }

}

