package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Score")
public class Score {
    private String scoreId;
    private Integer teamA;
    private Integer teamB;

    @DynamoDBHashKey(attributeName = "scoreId")
    @DynamoDBAutoGeneratedKey()
    public String getScoreId() {
        return scoreId;
    }

    public void setScoreId(String scoreId) {
        this.scoreId = scoreId;
    }
    @DynamoDBAttribute(attributeName="teamA")
    public Integer getTeamA() {
        return teamA;
    }

    public void setTeamA(Integer teamA) {
        this.teamA = teamA;
    }

    @DynamoDBAttribute(attributeName="teamB")
    public Integer getTeamB() {
        return teamB;
    }

    public void setTeamB(Integer teamB) {
        this.teamB = teamB;
    }
}
