package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.util.List;

@DynamoDBTable(tableName="SportsVenue")
@Builder
public class SportsVenues {

    private String cityId;
    private List<SportsVenue> sportsVenuesInCity;

    @DynamoDBHashKey(attributeName="cityId")
    public String getCityId() {
        return cityId;
    }

    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    @DynamoDBAttribute(attributeName="sportsVenuesInCity")
    public List<SportsVenue> getSportsVenuesInCity() {
        return sportsVenuesInCity;
    }

    public void setSportsVenuesInCity(List<SportsVenue> sportsVenuesInCity) {
        this.sportsVenuesInCity = sportsVenuesInCity;
    }

    @DynamoDBDocument
    @Builder
    @AllArgsConstructor
    public static class SportsVenue {
        private String sportsVenueId;
        private String displayName;
        private String googleMapsLink;
        private List<String> availableSportsIds;
        private StripePaymentLinkInput stripePaymentLinkInputs;

        @Builder.Default
        private StripePaymentLinkInput stripePaymentLinkInput = new StripePaymentLinkInput();

        public void setStripePaymentLinkInputs(StripePaymentLinkInput stripePaymentLinkInputs) {
            this.stripePaymentLinkInputs = stripePaymentLinkInputs;
        }

        @DynamoDBAttribute(attributeName="stripePaymentLinkInputs")
        public StripePaymentLinkInput getStripePaymentLinkInputs() {
            return stripePaymentLinkInputs;
        }

        @DynamoDBAutoGeneratedKey()
        @DynamoDBAttribute(attributeName="sportsVenueId")
        public String getSportsVenueId() {
            return sportsVenueId;
        }

        public void setSportsVenueId(String sportsVenueId) {
            this.sportsVenueId = sportsVenueId;
        }

        @DynamoDBAttribute(attributeName="displayName")
        public String getDisplayName() {
            return displayName;
        }

        public void setDisplayName(String displayName) {
            this.displayName = displayName;
        }

        @DynamoDBAttribute(attributeName="googleMapsLink")
        public String getGoogleMapsLink() {
            return googleMapsLink;
        }

        public void setGoogleMapsLink(String googleMapsLink) {
            this.googleMapsLink = googleMapsLink;
        }

        @DynamoDBAttribute(attributeName="availableSportsIds")
        public List<String> getAvailableSportsIds() {
            return availableSportsIds;
        }

        public void setAvailableSportsIds(List<String> availableSportsIds) {
            this.availableSportsIds = availableSportsIds;
        }

    }

    @Builder
    public static class StripePaymentLinkInput {
        private float amount;
        private String link;
        public StripePaymentLinkInput() {
        }

        public StripePaymentLinkInput(float amount, String link) {
            this.amount = amount;
            this.link = link;
        }
        @DynamoDBAttribute(attributeName="amount")
        public float getAmount() {
            return amount;
        }

        public void setAmount(float amount) {
            this.amount = amount;
        }
        @DynamoDBAttribute(attributeName="link")
        public String getLink() {
            return link;
        }

        public void setLink(String link) {
            this.link = link;
        }
    }
}
