package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.util.List;

@DynamoDBTable(tableName="SportsVenue")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SportsVenues {

    private String cityId;
    private List<SportsVenue> sportsVenuesInCity;

    @DynamoDBHashKey(attributeName="cityId")
    public String getCityId() {
        return cityId;
    }

    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    @DynamoDBAttribute(attributeName="sportsVenuesInCity")
    public List<SportsVenue> getSportsVenuesInCity() {
        return sportsVenuesInCity;
    }

    public void setSportsVenuesInCity(List<SportsVenue> sportsVenuesInCity) {
        this.sportsVenuesInCity = sportsVenuesInCity;
    }

    @DynamoDBDocument
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class SportsVenue {
        private String sportsVenueId;
        private String displayName;
        private String googleMapsLink;
        private List<String> availableSportsIds;
        private List<StripePaymentLink> stripePaymentLinks;
        private String pinCode;

        @DynamoDBAttribute(attributeName="pinCode")
        public String getPinCode() {
            return pinCode;
        }
        public void setPinCode(String pinCode) {
            this.pinCode = pinCode;
        }

        public List<StripePaymentLink> getStripePaymentLinks() {
            return stripePaymentLinks;
        }

        public void setStripePaymentLinks(List<StripePaymentLink> stripePaymentLinks) {
            this.stripePaymentLinks = stripePaymentLinks;
        }

        @DynamoDBAutoGeneratedKey()
        @DynamoDBAttribute(attributeName="sportsVenueId")
        public String getSportsVenueId() {
            return sportsVenueId;
        }

        public void setSportsVenueId(String sportsVenueId) {
            this.sportsVenueId = sportsVenueId;
        }

        @DynamoDBAttribute(attributeName="displayName")
        public String getDisplayName() {
            return displayName;
        }

        public void setDisplayName(String displayName) {
            this.displayName = displayName;
        }

        @DynamoDBAttribute(attributeName="googleMapsLink")
        public String getGoogleMapsLink() {
            return googleMapsLink;
        }

        public void setGoogleMapsLink(String googleMapsLink) {
            this.googleMapsLink = googleMapsLink;
        }

        @DynamoDBAttribute(attributeName="availableSportsIds")
        public List<String> getAvailableSportsIds() {
            return availableSportsIds;
        }

        public void setAvailableSportsIds(List<String> availableSportsIds) {
            this.availableSportsIds = availableSportsIds;
        }

    }

    @DynamoDBDocument
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class StripePaymentLink {

        Double amount;
        String url;

        @DynamoDBAttribute(attributeName="amount")
        public Double getAmount() {
            return amount;
        }

        public void setAmount(Double amount) {
            this.amount = amount;
        }

        @DynamoDBAttribute(attributeName="url")
        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
    }
}
