package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.ToString;

import java.time.LocalDate;

@DynamoDBTable(tableName = "SubscriptionDetails")
@ToString
@Data
public class SubscriptionDetails {

//    Here we have composite primary key of userId and passId which implies that a user can only buy a respective pass only once.

    private String userId;
    private String passId;
    private String passType;

    private String subscriptionId;
    private String subscriptionDetailsId;
    private String daysSubscriptionId;
    private String gamesSubscriptionId;

    @DynamoDBHashKey(attributeName="subscriptionDetailsId")
    @DynamoDBAutoGeneratedKey
    public String getSubscriptionDetailsId() {
        return subscriptionDetailsId;
    }

    public void setSubscriptionDetailsId(String subscriptionDetailsId) {
        this.subscriptionDetailsId = subscriptionDetailsId;
    }

    @DynamoDBAttribute(attributeName = "subscriptionId")
    public String getSubscriptionId() {
        return subscriptionId;
    }

    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    @DynamoDBAttribute(attributeName = "passType")
    public String getPassType() {
        return passType;
    }

    public void setPassType(String passType) {
        this.passType = passType;
    }

    @DynamoDBAttribute(attributeName = "userId")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "passId")
    public String getPassId() {
        return passId;
    }

    public void setPassId(String passId) {
        this.passId = passId;
    }


}
