package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.ToString;

@DynamoDBTable(tableName = "Subscription")
@ToString
@Data
public class Subscription {

    private String subscriptionId;
    public static enum Status {
        valid,
        expired;
    }
    private Status status;
    private String subscriptionDetailsId;
    private String createdDate;
    private String lastUpdatedDate;

    @DynamoDBHashKey(attributeName="subscriptionId")
    @DynamoDBAutoGeneratedKey
    public String getSubscriptionId() {
        return subscriptionId;
    }
    @DynamoDBAttribute(attributeName = "subscriptionDetailsId")
    public String getSubscriptionDetailsId() {
        return subscriptionDetailsId;
    }

    public void setSubscriptionDetailsId(String subscriptionDetailsId) {
        this.subscriptionDetailsId = subscriptionDetailsId;
    }

    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    @DynamoDBAttribute(attributeName = "createdDate")
    public String getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    @DynamoDBAttribute(attributeName = "lastUpdatedDate")
    public String getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(String lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }


    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedEnum
    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

}
