package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.time.LocalDate;

@DynamoDBTable(tableName = "SubscriptionDetails")
@ToString
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class SubscriptionDetails {

//    Here we have composite primary key of userId and passId which implies that a user can only buy a respective pass only once.

    private String userId;
    private String passId;
    private String passType;

    private String subscriptionId;
    private String subscriptionDetailsId;
    private String daysSubscriptionId;
    private String gamesSubscriptionId;


}
