package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;


@DynamoDBTable(tableName="Subscription")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Subscription {
    @DynamoDBHashKey(attributeName = "subscriptionId")
    @DynamoDBAutoGeneratedKey()
    private String subscriptionId;

    @DynamoDBAttribute(attributeName = "passId")
    private String passId;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "gamesLeft")
    private Integer gamesLeft;

    @DynamoDBAttribute(attributeName = "status")
    private String status;

    @DynamoDBAttribute(attributeName = "expiryDate")
    private String expiryDate;
}
