package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.ToString;

import java.time.LocalDate;

@DynamoDBTable(tableName = "Subscription")
@ToString
public class Subscription {
    private String subscriptionId;
    private String userId;
    private String passId;
    private LocalDate startDate;
    private LocalDate endDate;
    private Integer gamesUsed;
    private String status;
    private String passType;

    @DynamoDBAttribute(attributeName = "passType")
    public String getPassType() {
        return passType;
    }

    public void setPassType(String passType) {
        this.passType = passType;
    }

    @DynamoDBHashKey(attributeName="subscriptionId")
    @DynamoDBAutoGeneratedKey
    public String getSubscriptionId() {
        return subscriptionId;
    }

    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    @DynamoDBIndexHashKey(attributeName="userId", globalSecondaryIndexName="UserIdIndex")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBIndexHashKey(attributeName="passId", globalSecondaryIndexName="PassIdIndex")
    public String getPassId() {
        return passId;
    }

    public void setPassId(String passId) {
        this.passId = passId;
    }

    @DynamoDBHashKey(attributeName="startDate")
    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    @DynamoDBHashKey(attributeName="endDate")
    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    @DynamoDBHashKey(attributeName="gamesUsed")
    public Integer getGamesUsed() {
        return gamesUsed;
    }

    public void setGamesUsed(Integer gamesUsed) {
        this.gamesUsed = gamesUsed;
    }

    @DynamoDBHashKey(attributeName="status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
