package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.ArrayList;
import java.util.List;

@DynamoDBTable(tableName="User")
@ToString
public class User {

    private String email;
    private String name;
    private String phoneNumber;
    private String userId;
    private List<String> subscriptionHistory = new ArrayList<>();
    private Boolean hasActiveSubscription;
    private List<String> citiesHistory=new ArrayList<>();
    private List<String> userPinCodes = new ArrayList<>();

    @DynamoDBAttribute(attributeName="userPinCodes")
    public List<String> getUserPinCodes() {
        return userPinCodes;
    }

    public void setUserPinCodes(List<String> userPinCodes) {
        this.userPinCodes = userPinCodes;
    }

    @DynamoDBAttribute(attributeName="citiesHistory")
    public List<String> getCitiesHistory() {
        return citiesHistory;
    }

    public void setCitiesHistory(List<String> citiesHistory) {
        this.citiesHistory = citiesHistory;
    }


    @DynamoDBHashKey(attributeName="userId")
    @DynamoDBAutoGeneratedKey()
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName="email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName="name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName="phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    @DynamoDBAttribute(attributeName="subscriptionHistory")
    public List<String> getSubscriptionHistory() {
        return subscriptionHistory;
    }

    public void setSubscriptionHistory(List<String> subscriptionHistory) {
        this.subscriptionHistory = subscriptionHistory;
    }

    @DynamoDBAttribute(attributeName="hasActiveSubscription")
    public Boolean getHasActiveSubscription() {
        return hasActiveSubscription;
    }

    public void setHasActiveSubscription(Boolean hasActiveSubscription) {
        this.hasActiveSubscription = hasActiveSubscription;
    }


}
