package com.flickmatch.platform.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.ToString;

@DynamoDBTable(tableName="User")
@ToString
public class User {

    private String email;
    private String name;
    private String phoneNumber;
    private String userId;

    boolean isSubscribed;
    private String subscriptionValidFrom;
    private String subscriptionValidTo;
    private String subscriptionPassId;

    public boolean isSubscribed() {
        return isSubscribed;
    }

    public void setSubscribed(boolean subscribed) {
        isSubscribed = subscribed;
    }

    @DynamoDBAttribute(attributeName="subscriptionValidFrom")
    public String getSubscriptionValidFrom() {
        return subscriptionValidFrom;
    }

    public void setSubscriptionValidFrom(String subscriptionValidFrom) {
        this.subscriptionValidFrom = subscriptionValidFrom;
    }

    @DynamoDBAttribute(attributeName="subscriptionValidTo")
    public String getSubscriptionValidTo() {
        return subscriptionValidTo;
    }

    public void setSubscriptionValidTo(String subscriptionValidTo) {
        this.subscriptionValidTo = subscriptionValidTo;
    }

    @DynamoDBAttribute(attributeName="subscriptionPassId")
    public String getSubscriptionPassId() {
        return subscriptionPassId;
    }

    public void setSubscriptionPassId(String subscriptionPassId) {
        this.subscriptionPassId = subscriptionPassId;
    }

    @DynamoDBHashKey(attributeName="userId")
    @DynamoDBAutoGeneratedKey()
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName="email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName="name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName="phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}
