name: Deploy to Elastic Beanstalk

on:
  push:
    branches: ["main"]
    paths:
      - "platform/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy-to-eb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew clean build -Dspring.profiles.active=prod
        working-directory: platform
      - name: List build artifacts
        run: ls -l platform/build/libs

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "flickmatch-platform"
          environment_name: "Flickmatch-platform-env"
          version_label: ${{ github.sha }}
          region: ap-south-1
          use_existing_version_if_available: true
          deployment_package: platform/build/libs/platform-0.0.1-SNAPSHOT.war
