# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Integration - Platform

on:
  push:
    branches: ["main"]
    paths:
      - "platform/**"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
      - name: Create .env file
      - run: |
          touch .env
          echo SPRING_GRAPHQL_CORS_ALLOWED_ORIGIN=${{ secrets.SPRING_GRAPHQL_CORS_ALLOWED_ORIGIN }} >> .env
          echo PROD_DYNAMODB_ENDPOINT=${{ secrets.PROD_DYNAMODB_ENDPOINT }} >> .env
          echo PROD_AWS_REGION=${{ secrets.PROD_AWS_REGION }} >> .env
          echo PROD_AWS_PROFILE=${{ secrets.PROD_AWS_PROFILE }} >> .env
          echo PROD_PHONEPE_MERCHANT_ID=${{ secrets.PROD_PHONEPE_MERCHANT_ID }} >> .env
          echo PROD_PHONEPE_SALT_KEY=${{ secrets.PROD_PHONEPE_SALT_KEY }} >> .env
          echo PROD_PHONEPE_SALT_KEY_INDEX=${{ secrets.PROD_PHONEPE_SALT_KEY_INDEX }} >> .env
          echo PROD_WHATSAPP_ENDPOINT=${{ secrets.PROD_WHATSAPP_ENDPOINT }} >> .env
          echo PROD_RAZORPAY_KEY_ID=${{ secrets.PROD_RAZORPAY_KEY_ID }} >> .env
          echo PROD_RAZORPAY_KEY_SECRET=${{ secrets.PROD_RAZORPAY_KEY_SECRET }} >> .env
          echo PROD_TWILIO_ACCOUNT_SID=${{ secrets.PROD_TWILIO_ACCOUNT_SID }} >> .env
          echo DEV_AWS_REGION=${{ secrets.DEV_AWS_REGION }} >> .env
          echo DEV_AWS_PROFILE=${{ secrets.DEV_AWS_PROFILE }} >> .env
          echo DEV_PHONEPE_MERCHANT_ID=${{ secrets.DEV_PHONEPE_MERCHANT_ID }} >> .env
          echo DEV_PHONEPE_SALT_KEY=${{ secrets.DEV_PHONEPE_SALT_KEY }} >> .env
          echo DEV_PHONEPE_SALT_KEY_INDEX=${{ secrets.DEV_PHONEPE_SALT_KEY_INDEX }} >> .env
          echo DEV_WHATSAPP_ENDPOINT=${{ secrets.DEV_WHATSAPP_ENDPOINT }} >> .env
          echo DEV_RAZORPAY_KEY_ID=${{ secrets.DEV_RAZORPAY_KEY_ID }} >> .env
          echo DEV_RAZORPAY_KEY_SECRET=${{ secrets.DEV_RAZORPAY_KEY_SECRET }} >> .env
          echo DEV_TWILIO_ACCOUNT_SID=${{ secrets.DEV_TWILIO_ACCOUNT_SID }} >> .env
          echo BETA_DYNAMODB_ENDPOINT=${{ secrets.BETA_DYNAMODB_ENDPOINT }} >> .env
          echo BETA_AWS_REGION=${{ secrets.BETA_AWS_REGION }} >> .env
          echo BETA_AWS_PROFILE=${{ secrets.BETA_AWS_PROFILE }} >> .env
          echo BETA_PHONEPE_MERCHANT_ID=${{ secrets.BETA_PHONEPE_MERCHANT_ID }} >> .env
          echo BETA_PHONEPE_SALT_KEY=${{ secrets.BETA_PHONEPE_SALT_KEY }} >> .env
          echo BETA_PHONEPE_SALT_KEY_INDEX=${{ secrets.BETA_PHONEPE_SALT_KEY_INDEX }} >> .env
          echo BETA_WHATSAPP_ENDPOINT=${{ secrets.BETA_WHATSAPP_ENDPOINT }} >> .env
          echo BETA_RAZORPAY_KEY_ID=${{ secrets.BETA_RAZORPAY_KEY_ID }} >> .env
          echo BETA_RAZORPAY_KEY_SECRET=${{ secrets.BETA_RAZORPAY_KEY_SECRET }} >> .env
          echo BETA_TWILIO_ACCOUNT_SID=${{ secrets.BETA_TWILIO_ACCOUNT_SID }} >> .env
          cat .env
      - name: Setup Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      - name: Execute Gradle build
        run: gradle clean build
        working-directory: platform
      - name: Deploy to tomcat
        run: curl -v -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} -T ${{ secrets.WAR_FILE_PATH }} ${{ secrets.AMAZON_EC2_ADDRESS }}
